# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="MVZ"
DIST_VERSION="0.921"


inherit perl-module

DESCRIPTION="Parses .msg message files as produced by Microsoft Outlook."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND="dev-perl/Module-Build
        dev-lang/perl"

RDEPEND="dev-perl/Email-Address
         dev-perl/Email-MIME
         dev-perl/Email-Sender
         dev-perl/Email-Simple
         dev-perl/IO-String
         dev-perl/OLE-StorageLite"
