#!/sbin/openrc-run
description="ma1sd log daemon"
pidfile=${pidfile:-"/run/${RC_SVCNAME}.pid"}
user=${user:-${RC_SVCNAME}}
group=${group:-${RC_SVCNAME}}

command="/usr/bin/ma1sd"
command_args="${command_args:--c=/etc/ma1sd/ma1sd.yaml}"
command_background="true"
start_stop_daemon_args="--user ${user} --group ${group} \
        --stdout /var/log/${RC_SVCNAME}.log \
        --stderr /var/log/${RC_SVCNAME}.log"

depend() {
        after net
}

